### ISSUE TITLE
About the source_only model

### ISSUE THREAD

**Issue by qpc1611094** [DZhaoXd/DT-ST#2]
Hello, thank you for your work.
I evaluate that the source-only 'G2C_model_iter020000.pth', and get a performance of miou=43.27, thus it is the "source model+DG" in paper;
And I evaluate the source-only 'S2C_model_iter020000.pth', and get a performance of miou(16class) = 32.10, thus it is the "source model" in paper.

Could you kindly provide the other two source-only models? ("GTA5 source model" and "SYNTHIA source model+DG")

**Comment by DZhaoXd** [comment]
Ok, I will update all pretrained models soon.

**Comment by qpc1611094** [comment]
Thanks for your nice work!

**Comment by DZhaoXd** [comment]
Hello, I have updated the pre-trained model in https://drive.google.com/drive/folders/1MINE4So10eXdXA2mDJtxMagspExDtvB8?usp=drive_link .   Due to the instability of cross-domain segmentation, these pre-trained may deviate slightly (+- 1%) from the one reported in the paper, but it does not affect the performance after adaptation.  Hope it helps you.
